// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8YFoGSbMIrQxVHejS04hRmiCQgBB6SOk',
    appId: '1:128004902116:web:a2c799a2f857c6e646b0f1',
    messagingSenderId: '128004902116',
    projectId: 'habitify-34d82',
    authDomain: 'habitify-34d82.firebaseapp.com',
    storageBucket: 'habitify-34d82.firebasestorage.app',
    measurementId: 'G-KW16C84E59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGAWZwGF75X7l9-a2CC_c4ZgLpYh8vfMw',
    appId: '1:128004902116:android:2ff0891c9dcd250c46b0f1',
    messagingSenderId: '128004902116',
    projectId: 'habitify-34d82',
    storageBucket: 'habitify-34d82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA964M5c-0KmjWoQjZhnb92TZd1mi5LM-s',
    appId: '1:128004902116:ios:ebed3cda0755da6246b0f1',
    messagingSenderId: '128004902116',
    projectId: 'habitify-34d82',
    storageBucket: 'habitify-34d82.firebasestorage.app',
    iosClientId: '128004902116-5qcrdndsedc8d48koi10ihnjpld6tjv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA964M5c-0KmjWoQjZhnb92TZd1mi5LM-s',
    appId: '1:128004902116:ios:ebed3cda0755da6246b0f1',
    messagingSenderId: '128004902116',
    projectId: 'habitify-34d82',
    storageBucket: 'habitify-34d82.firebasestorage.app',
    iosClientId: '128004902116-5qcrdndsedc8d48koi10ihnjpld6tjv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8YFoGSbMIrQxVHejS04hRmiCQgBB6SOk',
    appId: '1:128004902116:web:2e6c67cbde74bf6346b0f1',
    messagingSenderId: '128004902116',
    projectId: 'habitify-34d82',
    authDomain: 'habitify-34d82.firebaseapp.com',
    storageBucket: 'habitify-34d82.firebasestorage.app',
    measurementId: 'G-VMT9H9SERB',
  );

}